### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ComFreek** [IonicaBizau/cli-github#1]
Hello Ionică,

I've just checked this out, but it throws an unspecified error - on Windows at least. I guess there is no Windows support.
```
P:\>github

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

P:\>
```

Don't feel forced to implement support for Windows now, I just wanted to check whether this behavior is 'intended' or not ;)

**Comment by IonicaBizau** [comment]
@ComFreek Can you please this on Windows 10? Would be curious what's the state of this issue.

**Comment by IonicaBizau** [comment]
Closing due to no response. Feel free to contribute making `cli-github` friendlier on Windows. :balloon:

**Comment by senthilporunan** [comment]
After i installed ImageMagick-6.9.2 in my MAC machine. I am facing the similar issue. 

/Users/senthil/Projects/temp/cli-github/bin/github:87
    if (err) { throw err; }
               ^

Error: spawn gm ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)

**Comment by IonicaBizau** [comment]
@senthilporunan You should install `graphicsmagic` instead. :art:
