### ISSUE TITLE
using 2FA with cli-github

### ISSUE THREAD

**Issue by timurb** [IonicaBizau/cli-github#18]
How should I use 2FA with cli-github?

Right now my transcript looks like the following:
```
║                                                                                  Logging in ...                                                                                 GitHub Username: timurb
GitHub Password:
2FA Authentication Code:
```

I've tried pasting the tokens generated at https://github.com/settings/applications but these do not work and I have received no auth codes to my mobile.
Do you think I have some issue with 2FA configured or using cli-github with 2FA or have I missed something during the configuration?

**Comment by IonicaBizau** [comment]
You will receive a SMS message on your phone, containing the authentication code. Write that code there.

If you didn't receive any auth codes on mobile, then that's most probably an issue with GitHub. But I will test it if it works for me.

**Comment by IonicaBizau** [comment]
/cc @remixz Can you look at [this part of code](https://github.com/IonicaBizau/cli-github/blob/add9782d1c0408362c4a156e9bdafda8c98be613/lib/api/login.js#L101-L107)? Do you see anything wrong?

At what step is GitHub supposed to send the SMS message? Probably [here](https://github.com/IonicaBizau/cli-github/blob/add9782d1c0408362c4a156e9bdafda8c98be613/lib/api/login.js#L90-L92)?

**Comment by IonicaBizau** [comment]
@timurb Run `npm install cli-github@latest` so you get `1.6.1` which should work fine with two factor authentication.

**Comment by timurb** [comment]
Works fine now, thanks!

**Comment by IonicaBizau** [comment]
Cool!
