### ISSUE TITLE
what's error

### ISSUE THREAD

**Issue by CreatorB** [IonicaBizau/cli-github#20]
![cli-git-error](https://cloud.githubusercontent.com/assets/6529730/6567082/967f3f4a-c6f4-11e4-9ea4-4c30c3ccac72.png)

Hi bizau, I have been clone your repo, and run locally but getting error like that, can you tell me about that?

**Comment by IonicaBizau** [comment]
Run `npm install` to install the dependencies. Then it should work.

**Comment by CreatorB** [comment]
owh sure sir... yesterday night, I 've run it too but still getting error because I forgot to hit it as root. hahhah maybe i feel sleepy. sorry about my mistake :) nice repo

**Comment by IonicaBizau** [comment]
:+1: :smile:
