### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by y12uc231** [IonicaBizau/cli-github#22]
After typing the command 'npm install -g cli-github' in the terminal, I got the following error

```sh
npm http GET https://registry.npmjs.org/cli-github

npm ERR! Error: failed to fetch from registry: cli-github
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/satya/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.0-29-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "cli-github"
npm ERR! cwd /home/satya
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: cli-github
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/satya/npm-debug.log
npm not ok
````

**Comment by IonicaBizau** [comment]
Looks like a temporary bug in `npm`. Could you try again and see if you can reproduce the error?

Also, please update the `npm` to latest version.

**Comment by y12uc231** [comment]
I used ' npm install -g npm' to upgrade my npm but it still showed the following error.

npm http GET https://registry.npmjs.org/npm

npm ERR! Error: failed to fetch from registry: npm
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/satya/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.0-29-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "npm"
npm ERR! cwd /home/satya
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: npm
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/satya/npm-debug.log
npm not ok

**Comment by IonicaBizau** [comment]
Most probably it has to do with your local settings. Try to do this:

```sh
npm config set registry https://registry.npmjs.org/
```

BTW, how did you install `npm` and `node`?

**Comment by y12uc231** [comment]
'sudo apt-get install node'

and 

sudo apt-get install npm

**Comment by IonicaBizau** [comment]
@y12uc231 Well, that's a wrong way to install NodeJS. Do it from PPA. You can use my script:

````sh
curl https://raw.githubusercontent.com/IonicaBizau/dotfiles/master/apps/node.sh | sh
```

**Comment by y12uc231** [comment]
an for npm?

On Tue, Apr 28, 2015 at 10:46 AM, Ionică Bizău <notifications@github.com>
wrote:

> @y12uc231 <https://github.com/y12uc231> Well, that's a wrong way to
> install NodeJS. Do it from PPA. You can use my script:
>
> curl https://raw.githubusercontent.com/IonicaBizau/dotfiles/master/apps/node.sh | sh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IonicaBizau/cli-github/issues/22#issuecomment-96912604>
> .
>



-- 
Regards,
Satyapriya Krishna
3rd Year Undergraduate,
Computer Science Dept.
The LNMIIT,Jaipur

**Comment by IonicaBizau** [comment]
@y12uc231 Both will be installed.

**Comment by y12uc231** [comment]
thanks

**Comment by IonicaBizau** [comment]
:+1: You're welcome!
