### ISSUE TITLE
Every character of my login I type doubled

### ISSUE THREAD

**Issue by kirushyk** [IonicaBizau/cli-github#25]
`══════════════════════════════════════════════════════╝
GitHub Username: kkiirruusshhyykk
GitHub Password: 
error:   Invalid input for GitHub Password:
error:   Invalid password.
GitHub Password: 
`

**Comment by IonicaBizau** [comment]
@kirushyk Thanks for heads up!! :open_mouth: I reproduced this using Node 4.0.0. If I switch back to older versions of Node, the problem doesn't appear.

I will take a look soon. Contributions are more than welcome too! :smile:

**Comment by IngwiePhoenix** [comment]
Same problem, can't use this program... sadly.
Please fix it soon, thanks :)

**Comment by IonicaBizau** [comment]
I tried to debug it, but I have no idea why this is happening... :sob: Help is more than welcome...

The workaround is to `nvm use v0.12.6` for now...
