### ISSUE TITLE
process.argv.includes is not a function

### ISSUE THREAD

**Issue by chrisbward** [IonicaBizau/cli-github#37]
Requires NodeJS 6, might want to update the docs?

**Comment by IonicaBizau** [comment]
Whoups, I'll actually not use `includes` yet.

**Comment by IonicaBizau** [comment]
Just tested with `v0.12.18` and fixed a bunch of issues in other packages that were containing ES6. Now, the code published on npm is transpiled and this tool works on antique versions of Node.js too! :grin:
