### ISSUE TITLE
NPM installation errors

### ISSUE THREAD

**Issue by iandstanley** [IonicaBizau/cli-github#39]
npm installation errors, npm install completes but can't run

Any ideas what is wrong here beyond the depricated dependancies

<details>
`
iandstanley:~/workspace (master) $ npm i -g cli-github
/home/ubuntu/.nvm/versions/node/v6.9.4/bin/github -> /home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/cli-github/bin/github

\> lwip2@1.0.7 install /home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/cli-github/node_modules/lwip2
\> node lib/install.js

Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

\> lwip@0.0.8 install /home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/lwip
\> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/lwip/build'
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../node_modules/nan/nan.h:182:0,
                 from ../src/decoder/decoder.h:13,
                 from ../src/decoder/init.cpp:1:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../node_modules/nan/nan_maybe_43_inl.h:221:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated (declared at /home/ubuntu/.node-gyp/6.9.4/include/node/v8.h:3031): Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from ../node_modules/nan/nan_new.h:189:0,
                 from ../node_modules/nan/nan.h:188,
                 from ../src/decoder/decoder.h:13,
                 from ../src/decoder/init.cpp:1:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../node_modules/nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated (declared at /home/ubuntu/.node-gyp/6.9.4/include/node/v8.h:4007): Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from ../src/decoder/decoder.h:13:0,
                 from ../src/decoder/init.cpp:1:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:591:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:596:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:596:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:601:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:601:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:602:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:607:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:607:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1933:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated (declared at /home/ubuntu/.node-gyp/6.9.4/include/node/v8.h:2750): Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
make: Leaving directory `/home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/lwip/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.2.0-c9
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v6.9.4/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/lwip
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.4/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.4/bin/npm" "i" "lwip@0.0.8"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.8 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/cli-github/node_modules/lwip2/npm-debug.log
/home/ubuntu/.nvm/versions/node/v6.9.4/lib
└─┬ cli-github@1.8.9 
  ├─┬ cli-box@6.0.5 
  │ ├── ansi-parser@3.2.5 
  │ ├── deffy@2.2.2 
  │ ├── is-undefined@1.0.5 
  │ ├── is-win@1.0.4 
  │ └── ul@5.2.9 
  ├─┬ cli-update@3.2.2 
  │ ├── cli-resize@2.0.2 
  │ └── cli-size@1.0.3 
  ├─┬ couleurs@6.0.6 
  │ ├─┬ ansy@1.0.6 
  │ │ ├── ansi-styles@2.1.0  (git://github.com/chalk/ansi-styles.git#5dadc5c6333127f95dc0dc09ada4fbde8bf66e69)
  │ │ ├── custom-return@1.0.4 
  │ │ └─┬ supports-color@3.1.2 
  │ │   └── has-flag@1.0.0 
  │ ├─┬ color-convert@1.8.2 
  │ │ └── color-name@1.1.1 
  │ ├── iterate-object@1.3.2 
  │ └─┬ typpy@2.3.6 
  │   └── function.name@1.0.5 
  ├─┬ github@7.3.2 
  │ ├─┬ follow-redirects@0.0.7 
  │ │ ├─┬ debug@2.6.0 
  │ │ │ └── ms@0.7.2 
  │ │ └── stream-consume@0.1.0 
  │ ├─┬ https-proxy-agent@1.0.0 
  │ │ └─┬ agent-base@2.0.1 
  │ │   └── semver@5.0.3 
  │ ├── mime@1.3.4 
  │ └── netrc@0.1.4 
  ├── idy@1.2.5 
  ├─┬ image-to-ascii@3.0.5 
  │ ├─┬ asciify-pixel-matrix@1.0.6 
  │ │ └─┬ asciify-pixel@1.2.6 
  │ │   ├── pixel-bg@1.0.5 
  │ │   └── pixel-white-bg@1.0.4 
  │ ├─┬ compute-size@1.0.5 
  │ │ ├─┬ fixed-or-percent@1.0.5 
  │ │ │ ├─┬ is-percent@1.0.6 
  │ │ │ │ └── last-char@1.3.5 
  │ │ │ └── percent-value@1.0.4 
  │ │ └── map-o@2.0.5 
  │ ├─┬ image-parser@1.2.2 
  │ │ ├── cb-buffer@2.1.1 
  │ │ ├── err@1.1.1 
  │ │ ├─┬ gm-tools@1.0.5 
  │ │ │ ├─┬ gm@1.23.0 
  │ │ │ │ ├── array-parallel@0.1.3 
  │ │ │ │ ├── array-series@0.1.5 
  │ │ │ │ ├─┬ cross-spawn@4.0.2 
  │ │ │ │ │ ├─┬ lru-cache@4.0.2 
  │ │ │ │ │ │ ├── pseudomap@1.0.2 
  │ │ │ │ │ │ └── yallist@2.0.0 
  │ │ │ │ │ └─┬ which@1.2.12 
  │ │ │ │ │   └── isexe@1.1.2 
  │ │ │ │ └─┬ debug@2.2.0 
  │ │ │ │   └── ms@0.7.1 
  │ │ │ ├── pngjs@2.3.1 
  │ │ │ └─┬ same-time@2.3.2 
  │ │ │   └── deffy@2.0.0 
  │ │ ├─┬ lwipify@2.0.6 
  │ │ │ ├─┬ lwip2@1.0.7 
  │ │ │ │ └─┬ gm-installed@1.0.4 
  │ │ │ │   └── prgm-installed@1.0.5 
  │ │ │ ├─┬ tinyreq@3.2.0 
  │ │ │ │ └── follow-redirects@0.2.0 
  │ │ │ └─┬ url-remote@1.1.3 
  │ │ │   └─┬ url-local@1.1.3 
  │ │ │     └─┬ parse-url@1.3.5 
  │ │ │       ├── is-ssh@1.3.0 
  │ │ │       └── protocols@1.4.3 
  │ │ ├── noop6@1.0.4 
  │ │ └── pixel-class@1.0.4 
  │ ├─┬ imgpx@1.0.7 
  │ │ └── lwip-pixels@1.1.4 
  │ ├─┬ one-by-one@3.2.3 
  │ │ ├── obj-def@1.0.3 
  │ │ └── sliced@1.0.1 
  │ └─┬ terminal-char-width@1.0.4 
  │   └── is-windows@0.1.1 
  ├── keypress@0.2.1 
  ├── le-table@6.1.4 
  ├── moment@2.17.1 
  ├─┬ overlap@2.2.5 
  │ ├── ansi-parser@3.0.0 
  │ ├─┬ cli-box@5.0.0 
  │ │ └─┬ ul@5.0.0 
  │ │   └── deffy@2.0.0 
  │ └─┬ couleurs@5.0.0 
  │   ├── flat-colors@3.0.0 
  │   ├── typpy@2.0.0 
  │   └── x256@0.0.2 
  ├── promptify@1.0.1 
  ├─┬ request@2.79.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.5.0 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@2.1.2 
  │ │ └── asynckit@0.4.0 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ chalk@1.1.3 
  │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ │ └── ansi-regex@2.0.0 
  │ │ │ ├── strip-ansi@3.0.1 
  │ │ │ └── supports-color@2.0.0 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ ├─┬ is-my-json-valid@2.15.0 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ ├── jsonpointer@4.0.1 
  │ │ │ └── xtend@4.0.1 
  │ │ └─┬ pinkie-promise@2.0.1 
  │ │   └── pinkie@2.0.4 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.3.1 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.10.1 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.0 
  │ │   ├─┬ dashdash@1.14.1 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.14.5 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.13 
  │ │ └── mime-db@1.25.0 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.3.0 
  │ ├── stringstream@0.0.5 
  │ ├─┬ tough-cookie@2.3.2 
  │ │ └── punycode@1.4.1 
  │ ├── tunnel-agent@0.4.3 
  │ └── uuid@3.0.1 
  └─┬ xml2js@0.4.17 
    ├── sax@1.2.1 
    └─┬ xmlbuilder@4.2.1 
      └── lodash@4.17.4 

iandstanley:~/workspace (master) $ 
iandstanley:~/workspace (master) $ 
iandstanley:~/workspace (master) $ 
iandstanley:~/workspace (master) $ github

/home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/cli-github/bin/github:74
    if (err) { throw err; }
               ^
Error: Stream yields empty buffer,Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "/home/ubuntu/.nvm/versions/node/v6.9.4/lib/node_modules/cli-github/resources/github.png" this most likely means the gm/convert binaries can't be found
iandstanley:~/workspace (master) $`
</details>

**Comment by IonicaBizau** [comment]
Hmm, looks like you do not have GraphicsMagick and lwip installation fails.

Can you install [`graphicsmagick`](https://github.com/IonicaBizau/cli-github#prerequisites) and try again?

```sh
sudo apt-get install graphicsmagick
```
