### ISSUE TITLE
Support login without password but token

### ISSUE THREAD

**Issue by PeterDaveHello** [IonicaBizau/cli-github#48]
Hi @IonicaBizau 
Is there any plan to support login via GitHub token instance of password?
Thanks!

**Comment by IonicaBizau** [comment]
You can simply enter a token instead of password.

Or store the token in the config file, before starting the app.

**Comment by brona90** [comment]
Which config file?

**Comment by IonicaBizau** [comment]
@brona90 The config file is located at `~/.github-config.json`. It will be created automatically. The quickest way is to enter a token instead of the password in the password field. Cheers!
